version: '3.9'
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - grafana-net
    ports:
      - 8125:8125/udp

  influxdb:
    image: influxdb:1.0
    container_name: influxdb
    env_file: configuration.env
    networks:
      - grafana-net
    ports:
      - 8086:8086
      - 8083:8083
      - 25826:25826/udp
    volumes:
      - ./:/imports
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    networks:
      - grafana-net
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana: {}
  influxdb: {}

networks:
  grafana-net:
    driver: bridge